spring:
  application:
    name: spring-transactions-workshop
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    # Transaction lifecycle logs
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    # Hibernate parameter binding logs
    org.hibernate.orm.jdbc.bind: TRACE

